version: "2.35.1"

services:
  banco:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algafood
    ports:
      - 3307:3306
  banco-test:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algafood_test
    ports:
      - 3308:3306