spring.application.name=algafood-api
server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3307/algafood?createDatabaseIfNotExists=true&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.baselineOnMigrate = true

spring.jpa.hibernate.ddl-auto=update

# Esse dialect é inútil uma vez que eu estou usando as migrations para iniciar o meu banco toda vez que eu derrubo o container, logo ele não pode adicionar as foreign keys automaticamente e eu tenho que fazer manualmente de qualquer jeito!
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

