# Ambiente de configuração para caso eu queira reparar alguma migration via terminal

flyway.url = jdbc:mysql://localhost:3307/algafood?createDatabaseIfNotExists=true&serverTimeZone=UTC
flyway.user = root
flyway.password = root